- name: Create OpenSM configuration temporary files.
  command:
    cmd: "opensm --create-config {{ eseries_ib_opensm_config_path }}opensm.conf.tmp~
                 --priority {{ eseries_ib_opensm_subnet_priority }}
                 --log_file {{ eseries_ib_opensm_log_path }}opensm.log
                 --daemon"
  changed_when: false
  become: true

- name: Update the subnet_prefix in temporary files.
  lineinfile:
    path: "{{ eseries_ib_opensm_config_path }}opensm.conf.tmp~"
    regexp: '^subnet_prefix'
    line: "subnet_prefix {{ eseries_ib_opensm_subnet_prefix }}"
  changed_when: false
  become: true

- name: Check whether changes have been to the the OpenSM configuration files.
  command:
    cmd: "diff {{ eseries_ib_opensm_config_path }}opensm.conf.tmp~ {{ eseries_ib_opensm_config_path }}opensm.conf"
  register: diff_opensm_config
  changed_when: false
  failed_when: false
  become: true

- name: Update missing or changed OpenSM configuration files.
  command:
    cmd: "mv -f {{ eseries_ib_opensm_config_path }}opensm.conf.tmp~ {{ eseries_ib_opensm_config_path }}opensm.conf"
  register: update_opensm_config
  become: true
  when: diff_opensm_config['rc'] != 0

- name: Remove OpenSM configuration temporary files.
  file:
    state: absent
    path: "{{ eseries_ib_opensm_config_path }}opensm.conf.tmp~"
  changed_when: false
  become: true

- name: Determine whether OpenSM service needs to be running and/or updated.
  set_fact:
    opensm_running: true
    opensm_update: "{{ update_opensm_config['changed'] == True }}"
    opensm_type: "standard"
