- name: Determine expected dispatcher hooks.
  ansible.builtin.set_fact:
    hook_templates: |-
      {%- set hook_templates = [] -%}
      {%- for interface in eseries_ip_interfaces -%}
        {%- for template in interface['hook_templates'] | default(eseries_ip_default_hook_templates) -%}
          {%- set filename = template.split(".")[0] ~ "-" ~ interface["name"] -%}
          {%- if hook_templates.append({"filename": filename, "template": template, "interface": interface}) -%}{%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- hook_templates -}}

# Determine interface's up status.
- name: Get link status for interfaces.
  ansible.builtin.command: "ip -4 address show {{ item['name'] }}"
  changed_when: false
  register: link_info
  loop: "{{ eseries_ip_interfaces }}"
  become: true

- name: Determine interfaces that are UP.
  ansible.builtin.set_fact:
    up_interfaces: |-
      {%- set interfaces = [] -%}
      {%- for result in link_info["results"] if "state UP" in result["stdout"] -%}
        {%- if interfaces.append(result["item"]["name"]) -%}{%- endif -%}
      {%- endfor -%}
      {{- interfaces -}}

# Determine whether existing networkd dispatcher hooks need to be changed.
- name: Check for existing dispatcher hooks.
  ansible.builtin.stat:
    path: "{{ eseries_ip_networkd_dispatcher }}routable.d/{{ item['filename'] }}"
  register: hooks_stats
  loop: "{{ hook_templates }}"
  become: true

- name: Determine whether dispatcher hooks need to changed.
  ansible.builtin.template:
    src: "{{ item['template'] }}"
    dest: "{{ eseries_ip_networkd_dispatcher }}routable.d/{{ item['filename'] }}"
    mode: "0755"
    group: root
    owner: root
  register: hooks
  check_mode: true
  loop: "{{ hook_templates }}"
  become: true

- name: Bring down any changed hooks.
  ansible.builtin.shell: "{{ item }}"  # Shell is required since environment variables are required
  loop: "{{ hook_off_cmds }}"
  become: true
  vars:
    hook_off_cmds: |-
      {%- set hook_off_cmds = [] -%}
      {%- for hooks_result in hooks["results"] if hooks_result["changed"] -%}
        {%- set interface = hooks_result["item"]["interface"]["name"] -%}

        {%- for hooks_stats_result in hooks_stats["results"]
              if hooks_stats_result["item"]["interface"]["name"] == interface and
                 hooks_stats_result["stat"]["exists"] and interface in up_interfaces -%}
          {%- set hook_path = eseries_ip_networkd_dispatcher ~ "routable.d/" ~ hooks_result["item"]["filename"] -%}
          {%- if hook_off_cmds.append("IFACE=" ~ interface ~ " STATE=off " ~ hook_path) -%}{%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- hook_off_cmds -}}

- name: Create expected dispatcher hooks.
  ansible.builtin.template:
    src: "{{ item['template'] }}"
    dest: "{{ eseries_ip_networkd_dispatcher }}/routable.d/{{ item['filename'] }}"
    mode: "0755"
    group: root
    owner: root
  register: hooks
  loop: "{{ hook_templates }}"
  become: true

- name: Determine networkd dispatcher action directories.
  ansible.builtin.command: "find {{ eseries_ip_networkd_dispatcher }} -maxdepth 1 -type d"
  changed_when: false
  register: dispatcher_action_dirs

- name: Create expected networkd dispatcher hook symbolic links.
  ansible.builtin.file:
    state: link
    src: "{{ item[0] }}"
    path: "{{ item[1] }}"
  loop: "{{ link_paths }}"
  become: true
  vars:
    link_paths: |-
      {%- set action_dirs = [] -%}
      {%- for line in dispatcher_action_dirs["stdout_lines"] -%}
        {%- set action_dir = line | regex_replace("^.*\/([\w-]+)\.d$", "\\1") -%}
        {%- if action_dir != eseries_ip_networkd_dispatcher -%}
          {%- if action_dirs.append(action_dir) -%}{%- endif -%}
        {%- endif -%}
      {%- endfor -%}

      {%- set link_paths = [] -%}
      {%- for hook_template in hook_templates -%}
        {%- for action in ["off", "carrier", "degraded", "dormant", "no-carrier"] if action in action_dirs -%}
          {%- set src = eseries_ip_networkd_dispatcher ~ "routable.d/" ~ hook_template["filename"] -%}
          {%- set path = eseries_ip_networkd_dispatcher ~ action ~ ".d/" ~ hook_template["filename"] -%}
          {%- if link_paths.append([src, path]) -%}{%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- link_paths -}}

- name: Bring up any changed hooks when the interface configuration is unchanged.
  ansible.builtin.shell: "{{ item }}"  # Shell is required since environment variables are required
  loop: "{{ hook_routable_cmds }}"
  become: true
  vars:
    hook_routable_cmds: |-
      {%- set changed_interfaces = [] -%}
      {%- for result in interface_config_results if result["changed"] -%}
        {%- if changed_interfaces.append(result["item"]["name"]) -%}{%- endif -%}
      {%- endfor -%}

      {%- set hook_routable_cmds = [] -%}
      {%- for hooks_result in hooks["results"] if hooks_result["changed"] -%}
        {%- set interface = hooks_result["item"]["interface"]["name"] -%}

        {%- for hooks_stats_result in hooks_stats["results"]
              if hooks_stats_result["item"]["interface"]["name"] == interface and interface not in changed_interfaces and
                 hooks_stats_result["stat"]["exists"] and interface in up_interfaces -%}
          {%- set hook_path = eseries_ip_networkd_dispatcher ~ hooks_result["item"]["filename"] -%}
          {%- if hook_routable_cmds.append("IFACE=" ~ interface ~ " STATE=routable " ~ hook_path) -%}{%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- hook_routable_cmds -}}
