- name: Discover mapped-volume information from associated storage systems.
  import_role:
    name: common
    tasks_from: gather_storage_facts.yml

- name: Setup expected host protocol.
  include_tasks: protocol.yml

- name: Uninstall protocols.
  import_tasks: uninstall.yml
  tags:
    - never
    - protocol_uninstall