- name: Discover mapped-volume information from associated storage systems.
  include_role:
    name: common
    tasks_from: volume_facts.yml
  when: netapp_volumes_by_initiators is not defined

- name: Setup expected host protocol.
  include_tasks: protocol.yml

- name: Uninstall protocols.
  import_tasks: uninstall.yml
  tags:
    - never
    - protocol_uninstall