- name: Check whether /etc/multipath.conf exists
  stat:
    path: "/etc/multipath.conf"
  register: multipath_conf
  become: true
- name: Ensure that multipath.conf exists.
  file:
    state: touch
    path: "/etc/multipath.conf"
  when: not multipath_conf["stat"]["exists"]
  become: true

- name: Check whether multipath kernel module has been loaded.
  modprobe:
    state: present
    name: "{{ item }}"
  register: multipath_module
  loop: "{{ eseries_multipath_kernel_modules }}"
  become: true

- name: Ensure multipathd daemon has been started and is enabled.
  systemd:
    state: started
    name: multipathd.service
    enabled: true
  become: true