- name: Ensure multipath has been installed.
  block:
    - name: Ensure multipath packages are installed.
      include_tasks: package.yml
    - name: Ensure multipath is configured.
      include_tasks: configure.yml
  when: not eseries_multipath_remove_installation

- name: Uninstall multipath.
  block:
    - name: Uninstall multipath.
      include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - multipath_uninstall
