- name: Ensure multipath has been installed.
  block:
    - name: Ensure multipath packages are installed.
      include_tasks: package.yml
    - name: Ensure multipath is configured.
      include_tasks: configure.yml
  when: not eseries_multipath_remove_installation

- name: Uninstall multipath.
  import_tasks: uninstall.yml
  tags:
    - never
    - multipath_uninstall
