- name: Apply packages and settings for the appropriate distribution.  
  block:
    - ansible.builtin.include_tasks: distribution/redhat.yml
      when: ansible_facts['os_family'] | lower == 'redhat'
    - ansible.builtin.include_tasks: distribution/debian.yml
      when: ansible_facts['os_family'] | lower == 'debian'
    - name: Configure tuned when requested. 
      ansible.builtin.include_tasks: tuned.yml
      when: tune_performance_configure_tuned
  become: True

