- name: Ensure expected InfiniBand IPoIB packages are removed (SUSE).
  zypper:
    state: absent
    name: "{{ eseries_ib_opensm_suse_packages }}"
  become: true

- name: Create InfiniBand OpenSM service loader daemon for E-Series.
  file:
    state: absent
    path: "{{ eseries_ib_opensm_daemon_path }}eseries_opensm"
  become: true

- name: Create InfiniBand OpenSM service loader for E-Series.
  file:
    state: absent
    path: "{{ eseries_ib_opensm_service_path }}opensm.service"
  become: true
