- name: Determine the network manager (netplan, ifupdown, network_manager, networkd)
  ansible.builtin.include_tasks: get_manager.yml

- name: Ensure interface(s) are configured.
  ansible.builtin.include_tasks: interface.yml
  when: eseries_ip_base_configure_network

- name: Ensure firewall is configured.
  ansible.builtin.include_tasks: firewall.yml
  when: eseries_ip_base_configure_firewall

- name: Ensure interface(s) and firewall are unconfigured.
  block:
    - name: Unconfigure interface(s).
      ansible.builtin.include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - ip_base_uninstall
