namespace: "netapp_eseries"
name: "host"
version: "0.2.0"
readme: "README.md"
authors:
  - Nathan Swartz (@ndswartz)
dependencies:
  "ansible.posix": "*"
  "ansible.netcommon": "*"
  "community.general": "*"
  "netapp_eseries.santricity": ">=1.2.0"
license:
  - "BSD-3-Clause"
repository: "https://www.github.com/netappeseries/host"
tags:
  - netapp
  - eseries
  - santricity
  - storage
homepage: "https://www.github.com/netappeseries/host"
issues: "https://github.com/netappeseries/host/issues"
