namespace: "netapp_eseries"
name: "host"
version: "1.0.0"
readme: "README.md"
authors:
  - Nathan Swartz (@ndswartz)
dependencies:
  netapp_eseries.santricity: ">=1.0.8"
license:
  - "BSD-3-Clause"
repository: "https://www.github.com/netapp-eseries/host"
tags:
  - netapp
  - eseries
  - santricity
  - storage
homepage: "https://www.github.com/netapp-eseries/host"
issues: "https://github.com/netappeseries/host/issues"
