- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Determine variable values required for ipoib role.
  set_fact:
    eseries_ipoib_interfaces: "{{ eseries_ipoib_interfaces | default(eseries_ib_iser_interfaces | default(omit)) }}"
    eseries_ipoib_opensm_configure: "{{ eseries_ipoib_opensm_configure | default(eseries_ib_iser_opensm_configure | default(omit)) }}"
    eseries_ipoib_opensm_subnet_prefix: "{{ eseries_ipoib_opensm_subnet_prefix | default(eseries_ib_iser_opensm_subnet_prefix | default(omit)) }}"
    eseries_ipoib_opensm_subnet_priority: "{{ eseries_ipoib_opensm_subnet_priority | default(eseries_ib_iser_opensm_subnet_priority | default(omit)) }}"
    eseries_ipoib_mtu: "{{ eseries_ipoib_mtu | default(eseries_ib_iser_mtu | default(omit)) }}"

- name: Ensure InfiniBand IPoIB is uninstalled.
  import_role:
    name: ipoib
    tasks_from: uninstall.yml

- name: Ensure iSCSI packages are uninstalled.
  import_role:
    name: iscsi
    tasks_from: uninstall_packages.yml
