- name: Ensure iSCSI packages are uninstalled.
  ansible.builtin.include_role:
    name: netapp_eseries.host.iscsi
    tasks_from: uninstall/package.yml

- name: Ensure iSCSI is unconfigured.
  ansible.builtin.include_role:
    name: netapp_eseries.host.iscsi
    tasks_from: uninstall/configure.yml

- name: Ensure InfiniBand IPoIB is installed and configured.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ib_opensm
    tasks_from: uninstall.yml
    apply:
      vars:
        eseries_ib_opensm_interfaces: "{{ eseries_ib_iser_interfaces }}"

- name: Ensure InfiniBand IPoIB is uninstalled.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ipoib
    tasks_from: uninstall.yml
    apply:
      vars:
        eseries_ipoib_configure_network: "{{ eseries_ib_iser_configure_network }}"
        eseries_ipoib_configure_firewall: "{{ eseries_ib_iser_configure_firewall }}"
        eseries_ipoib_interfaces: "{{ eseries_ib_iser_interfaces }}"
        eseries_ipoib_interface_ignore_keys: "{{ eseries_ib_iser_interface_ignore_keys }}"
        eseries_ipoib_interface_common: "{{ eseries_ib_iser_interface_common }}"
        eseries_ipoib_interface_defaults: "{{ eseries_ib_iser_interface_defaults }}"
        eseries_ipoib_firewall_zone: "{{ eseries_ib_iser_firewall_zone }}"
        eseries_ipoib_default_hook_templates: "{{ eseries_ib_iser_default_hook_templates }}"
