- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand IPoIB is uninstalled.
  import_role:
    name: ipoib
    tasks_from: uninstall.yml

- name: Ensure iSCSI packages are uninstalled.
  import_role:
    name: netapp_eseries.host.iscsi
    tasks_from: uninstall_packages.yml
