- name: Determine packages to install (SUSE).
  set_fact:
    suse_packages: |-
      {%- set packages = [] -%}
      {%- if eseries_ib_base_ipoib_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["ipoib"] | default([])) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_iser_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["iser"] | default([])) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_srp_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["srp"] | default([])) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_nvme_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["nvme"] | default([])) -%}{%- endif -%}
      {%- endif -%}
      {{- packages | unique | sort -}}

- name: Ensure expected InfiniBand packages are installed (SUSE).
  community.general.zypper:
    state: present
    name: "{{ suse_packages }}"
  register: packages
  become: true
