eseries_common_group: eseries_storage_systems
eseries_common_allow_host_reboot: false
eseries_common_docker_host: unix://var/run/docker.sock
eseries_common_mapped_log_path: /var/log

eseries_mount_log_path: /var/log
