eseries_common_group: eseries_storage_systems
eseries_common_allow_host_reboot: false
eseries_common_force_skip_uninstall: false              # Forces to skip uninstallation when roles has been called dynamically with applied tags;
                                                        #   otherwise the applied tags are also applied to uninstallation.
eseries_common_package_group: common                    # This variable can be used to override the task name package group description.
eseries_common_allow_upgrades: false
eseries_common_skip_package_validation: false
eseries_common_custom_packages:
#  files:
#    "<source>": "<destination>"
#    ...
#  install:
#    add_packages: []
#    remove_packages: []
#    commands: []
#  uninstall:
#    packages: []
#    commands: []



eseries_common_docker_host: unix://var/run/docker.sock
eseries_common_ignore_volumes: []
eseries_common_target_scan_paths:
  scsi:
    sas: "for fp in /sys/class/sas_host/*/device/scsi_host/host*/scan; do echo '- - -' > $fp; done"
    fc: "for fp in /sys/class/fc_host/*/device/scsi_host/host*/scan; do echo '- - -' > $fp; done"
    ib_srp: "for fp in /sys/class/infiniband_srp/*/device/host*/scsi_host/host*/scan; do echo -n '- - -' > $fp; done"
    iscsi: "for fp in /sys/class/scsi_host/host*/scan; do echo '- - -' > $fp; done"
    ib_iser: "for fp in /sys/class/scsi_host/host*/scan; do echo '- - -' > $fp; done"
  nvme:
    nvme_ib: ""
    nvme_fc: ""
    nvme_roce: ""

# Volume Discovery Protocol Action Lists (Do not modify)
eseries_common_discovery_protocol_list: ["iscsi", "fc", "sas", "ib_srp", "ib_iser", "nvme_ib", "nvme_fc", "nvme_roce"]
eseries_common_discovery_rescan_iscsi_session_protocol_list: ["iscsi", "ib_iser"]
eseries_common_discovery_rescan_scsi_bus_protocol_list: ["iscsi", "fc", "sas", "ib_srp", "ib_iser"]
