- name: Ensure InfiniBand base packages are installed.
  include_tasks: "package/{{  ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand base is configured.
  import_tasks: configure.yml

- name: Uninstall InfiniBand base.
  block:
    - name: Uninstall InfiniBand base.
      include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - ib_base_uninstall
