- name: Allow users to optionally skip installation of InfiniBand packages if they just want to use the other roles.
  block:
    - name: Set facts required for ib_base role.
      ansible.builtin.set_fact:
        eseries_common_package_group: "InfiniBand base"
        eseries_common_custom_packages: "{{ eseries_ib_base_custom_packages | default({}) }}"
        eseries_common_allow_upgrades: "{{ eseries_ib_base_allow_upgrades | default(false) }}"
        eseries_common_skip_package_validation: "{{ eseries_ib_base_skip_package_validation | default(false) }}"

    - name: Install InfiniBand base.
      ansible.builtin.include_tasks: install.yml
      when: not (eseries_common_uninstall | default(eseries_ib_base_uninstall))

    - name: Uninstall InfiniBand base.
      ansible.builtin.include_tasks: uninstall.yml
      when: eseries_common_uninstall | default(eseries_ib_base_uninstall)
  when: not eseries_ib_base_skip
