- name: Uninstall InfiniBand base custom packages.
  ansible.builtin.include_role:
    name: netapp_eseries.host.common
    tasks_from: installer/uninstall.yml
  when: '"uninstall" in (eseries_common_custom_packages.keys() | list)'

- name: Ensure InfiniBand packages are uninstalled.
  ansible.builtin.include_tasks: "uninstall/package/{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand base kernel modules are removed.
  ansible.builtin.include_tasks: "uninstall/configure/module.yml"
