- name: Include operating specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}/interface/ifupdown.yml"

- name: Ensure ifupdown configuration files are removed for each interface.
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_ip_ifupdown_path }}ifcfg-{{ item['name'] }}"
  loop: "{{ eseries_ip_interfaces }}"
  become: true

- name: Delete address from interface.
  ansible.builtin.command: "ip address delete {{ item['address'] }} dev {{ item['name'] }}"
  register: ip_delete
  changed_when: ip_delete['rc'] == 0
  failed_when: false
  loop: "{{ eseries_ip_interfaces }}"
  become: true
