- name: Ensure udev rules exist for network interface mappings.
  ansible.builtin.template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'interface/rename_rules.j2') }}"
    dest: "{{ eseries_common_udev_rules_d }}{{ udev_name }}"
  register: interface_rename_rules
  when: udev_name and udev_rules
  become: true
  vars:
    udev_name: |-
      {%- if _common_udev_name is defined and _common_udev_name -%}
        {{- _common_udev_name -}}
      {%- else %}
        {{- eseries_common_udev_name -}}
      {%- endif -%}
    udev_rules: |-
      {%- if _common_udev_rules is defined and _common_udev_rules -%}
        {{- _common_udev_rules -}}
      {%- else %}
        {{- eseries_common_udev_rules -}}
      {%- endif -%}

- name: Reboot hosts to update interface name(s).
  ansible.builtin.include_role:
    name: common
    tasks_from: reboot.yml
    apply:
      vars:
        eseries_common_allow_host_reboot_reason: "Updated interface name(s).  Reboot is required."
  when: interface_rename_rules['changed']
