- name: Get information for all net devices.
  ansible.builtin.shell: |
    for device in $(ls /sys/class/net/); do
      echo "$device" \
           "$(cat /sys/class/net/$device/address)" \
           "$(grep -s PCI_SLOT_NAME=.* /sys/class/net/$device/device/uevent | cut -d '=' -f 2)"
    done
  changed_when: false
  register: net_devices
  become: true

- name: Apply udev rules and update interface names.
  block:
    - name: Ensure udev rules exist for network interface mappings.
      ansible.builtin.template:
        src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'interface/rename_rules.j2') }}"
        dest: "{{ eseries_common_udev_rules_d }}{{ eseries_common_udev_name }}"
      register: interface_rename_rules

    - name: Update interface names.
      ansible.builtin.include_tasks: interface/rename_rules/apply/update_interface.yml
      loop: "{{ eseries_common_udev_rules | dict2items }}"
      loop_control:
        loop_var: interface_rule
  when: eseries_common_udev_name and eseries_common_udev_rules
  become: true
  vars:
    interface_device_by_identifier: |-
      {%- set info = {} -%}
      {%- for net_device in net_devices["stdout_lines"] -%}
        {%- set net_device_info = net_device.split(" ") -%}
        {#- Create a dictionary entry for both the interface mac address and pci slot name -#}
        {%- if net_device_info | length == 3 -%}
          {%- if info.update({net_device_info[1]: {"type": "mac_address", "name": net_device_info[0]}}) -%}{%- endif -%}
          {%- if info.update({net_device_info[2]: {"type": "pci_slot_name", "name": net_device_info[0]}}) -%}{%- endif -%}
        {%- endif -%}
      {%- endfor -%}
      {{- info -}}
