- name: Ensure packages are installed.
  include_tasks: "package/{{ ansible_os_family | lower }}.yml"

- name: Discover mapped-volume information from associated storage systems.
  include_role:
    name: common
    tasks_from: host_facts.yml
  when: eseries_volumes is not defined

- name: Collect the required information for snapshot operations.
  include_tasks: collect_facts.yml

- name: Create snapshot consistency group point-in-time images.
  include_tasks: images.yml
  loop: "{{ pit_information }}"
  loop_control:
    loop_var: consistency_group
  run_once: true
