- name: Resume E-Series volume.
  ansible.builtin.command:
    cmd: "dmsetup resume /dev/mapper/{{ volumes['key'] }}"
  delegate_to: "{{ item['ansible_host_name'] }}"
  loop: "{{ volumes['value']['hosts'] }}"
  become: true
  when: eseries_snapshot_pit_safe == False and item['mounted'] == True

- name: "Wait for E-Series volume [{{ volumes['key'] }}] to be remounted."
  ansible.builtin.command:
    cmd: "mount /dev/mapper/{{ volumes['key'] }}"   # Options will be pulled from /etc/fstab
    warn: "{{ omit if ansible_version.major >= 2 and ansible_version.minor >= 14 else false }}"
  delegate_to: "{{ item['ansible_host_name'] }}"
  loop: "{{ volumes['value']['hosts'] }}"
  become: true
  when: eseries_snapshot_pit_safe == True and item['mounted'] == True
