galaxy_info:
  author: Nathan Swartz (@ndswartz)
  description: Setup storage communication with E-Series storage systems on the host.
  company: NetApp
  license: BSD-3-Clause
  min_ansible_version: 2.9
  galaxy_tags:
    - netapp
    - eseries
    - multipath
    - protocol
    - iscsi
    - ib
    - infiniband
    - iser
    - nvme
    - srp
    - fc
    - sas
dependencies: []
