- name: Ensure netplan ethernet interfaces configuration files have been removed.
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_ip_base_netplan_path }}99-eseries-ansible-{{ item['name'] }}.yaml"
  register: netplan
  loop: "{{ eseries_ip_base_interfaces }}"
  become: true

- name: Flush ethernet interface.
  ansible.builtin.command: ip address flush dev {{ item["name"] }}
  register: ip_flush
  changed_when: ip_flush['rc'] != 0
  failed_when: false
  loop: "{{ eseries_ip_base_interfaces }}"
  become: true

- name: Apply changes to Netplan
  ansible.builtin.command:
    cmd: netplan apply
  when: netplan['changed']
  become: true
