- name: Ensure udev rules exist for network interface mappings.
  ansible.builtin.template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'interface/udev/interface_mapping_rules.j2') }}"
    dest: "{{ eseries_common_udev_rules_d }}{{ eseries_common_udev_name }}"
  register: interface_mapping_rules
  when: eseries_common_udev_name and eseries_common_udev_rules

- name: Reboot hosts to update interface name(s).
  ansible.builtin.include_role:
    name: common
    tasks_from: reboot.yml
    apply:
      vars:
        eseries_common_allow_host_reboot_reason: "Updated interface name(s).  Reboot is required."
  when: interface_mapping_rules['changed']
