- name: Configure firewall zone and interfaces.
  block:
    - name: Ensure expected firewall zones exists.
      ansible.posix.firewalld:
        state: present
        zone: "{{ item['zone'] | default(eseries_common_firewall_zone) }}"
        permanent: true
        offline: true
      register: firewall_zone
      loop: "{{ eseries_common_interfaces }}"

    - name: Reload firewall to recognize the newly created zones.
      ansible.builtin.systemd:
        state: reloaded
        name: firewalld.service
      when: 'firewall_zone["changed"] and ansible_facts["services"]["firewalld.service"]["state"] == "running"'

    - name: Ensure expected firewall zones have the expected interfaces.
      ansible.posix.firewalld:
        state: enabled
        zone: "{{ item['zone'] | default(eseries_common_firewall_zone) }}"
        interface: "{{ item['name'] }}"
        immediate: true
        offline: true
      loop: "{{ eseries_common_interfaces }}"
  when: item["zone"] is defined or eseries_common_firewall_zone is defined
  become: true
