- name: Configure firewall zone and interfaces.
  block:
    - name: Ensure expected firewall zones exists.
      ansible.posix.firewalld:
        state: present
        zone: "{{ item['zone'] | default(eseries_common_firewall_zone) }}"
        permanent: true
        offline: true
      register: firewall_zone
      when: item['zone'] | default(eseries_common_firewall_zone | default(False))
      loop: "{{ eseries_common_interfaces }}"

    - name: Reload firewall to recognize the newly created zones.
      ansible.builtin.systemd:
        state: reloaded
        name: firewalld.service
      when: firewall_zone["changed"]

    - name: Ensure expected firewall zones have the expected interfaces.
      ansible.posix.firewalld:
        state: enabled
        zone: "{{ item['zone'] | default(eseries_common_firewall_zone) }}"
        interface: "{{ item['name'] }}"
        permanent: true
        immediate: true
        offline: true
      when: item['zone'] | default(eseries_common_firewall_zone | default(False))
      loop: "{{ eseries_common_interfaces }}"
  when: 'ansible_facts["services"]["firewalld.service"]["state"] == "running"'
  become: true
