- name: Ensure expected InfiniBand packages are installed (Ubuntu).
  ansible.builtin.apt:
    state: "{% if eseries_ib_opensm_allow_upgrades == True %}latest{% else %}present{% endif %}"
    name: "{{ eseries_ib_opensm_ubuntu_packages }}"
    allow_unauthenticated: "{{ eseries_ib_opensm_skip_package_validation }}"
  become: true
