- name: Ensure expected InfiniBand packages are installed (RHEL).
  ansible.builtin.yum:
    state: "{% if eseries_ib_opensm_allow_upgrades == True %}latest{% else %}present{% endif %}"
    name: "{{ eseries_ib_opensm_rhel_packages }}"
    disable_gpg_check: "{{ eseries_ib_opensm_skip_package_validation }}"
  become: true
