- name: Ensure expected InfiniBand packages are installed (SUSE).
  community.general.zypper:
    state: "{% if eseries_ib_opensm_allow_upgrades == True %}latest{% else %}present{% endif %}"
    name: "{{ eseries_ib_opensm_suse_packages }}"
  register: packages
  become: true
