- name: Ensure expected InfiniBand packages are installed (RHEL).
  yum:
    state: present
    name: "{{ eseries_ipoib_rhel_packages }}"
  register: packages
  become: true

- name: Install OpenSM if required (RHEL).
  yum:
    name: opensm
  become: true
  when: opensm_required == True
