- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Determine variable values required for ib_base role.
  set_fact:
    eseries_ib_base_ipoib_enabled: true

- name: Ensure InfiniBand base has been installed and configured.
  import_role:
    name: ib_base

- name: Ensure InfiniBand IPoIB is configured.
  import_tasks: configure.yml

- name: Uninstall InfiniBand IPoIB.
  block:
    - name: Uninstall InfiniBand IPoIB.
      include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - ipoib_uninstall
