- name: Ensure InfiniBand base has been installed and configured.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ib_base
    apply:
      vars:
        eseries_ib_base_ipoib_enabled: true

- name: Configure InfiniBand interfaces.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ip_base
    apply:
      vars:
        eseries_ip_base_configure_network: "{{ eseries_ipoib_configure_network }}"
        eseries_ip_base_configure_firewall: "{{ eseries_ipoib_configure_firewall }}"
        eseries_ip_base_interface_type: "{{ eseries_ipoib_interface_type }}"
        eseries_ip_base_interfaces: "{{ eseries_ipoib_interfaces }}"
        eseries_ip_base_interface_ignore_keys: "{{ eseries_ipoib_interface_ignore_keys }}"
        eseries_ip_base_interface_common: "{{ eseries_ipoib_interface_common }}"
        eseries_ip_base_interface_defaults: "{{ eseries_ipoib_interface_defaults }}"
        eseries_ip_base_firewall_zone: "{{ eseries_ipoib_firewall_zone }}"
        eseries_ip_base_default_hook_templates: "{{ eseries_ipoib_default_hook_templates }}"

- name: Uninstall InfiniBand IPoIB.
  block:
    - name: Uninstall InfiniBand IPoIB.
      ansible.builtin.include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - ipoib_uninstall
