- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure eseries_ipoib_interfaces inventory structure exists.
  set_fact:
    eseries_ipoib_interfaces: "{{ eseries_ib_iser_interfaces }}"
  when: eseries_ipoib_interfaces is not defined and eseries_ib_iser_interfaces is defined and eseries_ib_iser_interfaces

- name: Configure InfiniBand iSER network interfaces
  block:
    - name: Remove InfiniBand iSER network interfaces using ifupdown configuration.
      block:
        - name: Ensure ifcfg-* files exist for each InfiniBand iSER network interface (RHEL, SUSE).
          file:
            state: absent
            path: "{{ eseries_ipoib_ifcfg_path }}ifcfg-{{ item['name'] }}"
          register: ifcfg
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true

        - name: Bring InfiniBand iSER interface down using ifdown.
          command: ifdown {{ item['name'] }}
          register: ip_down
          changed_when: ip_down['rc'] != 0 and ip_down['stderr'] is not defined
          failed_when: false
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true

        - name: Flush InfiniBand iSER interface.
          command: ip address flush dev {{ item['name'] }}
          register: ip_flush
          changed_when: ip_flush['rc'] != 0 and ip_flush['stderr'] is not defined
          failed_when: false
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true
      when: eseries_ipoib_network_tool | default(eseries_ipoib_default_network_tool) == 'ifupdown'

    - name: Remove InfiniBand iSER network interfaces using netplan configuration.
      block:
        - name: Ensure InfiniBand iSER interfaces configuration files have been removed.
          file:
            state: absent
            path: "{{ eseries_ipoib_netplan_path }}99-eseries-ansible-{{ item['name'] }}.yaml"
          register: netplan
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true
        - name: Apply changes to Netplan
          command:
            cmd: netplan apply
          when: netplan['changed']
          become: true

        - name: Bring InfiniBand iSER interface down.
          command: ip link set {{ item["name"] }} down
          register: ip_down
          changed_when: ip_down['rc'] != 0 and ip_down['stderr'] is not defined
          failed_when: false
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true

        - name: Flush InfiniBand iSER interface.
          command: ip address flush dev {{ item["name"] }}
          register: ip_flush
          changed_when: ip_flush['rc'] != 0 and ip_flush['stderr'] is not defined
          failed_when: false
          loop: "{{ eseries_ipoib_interfaces }}"
          become: true
      when: eseries_ipoib_network_tool | default(eseries_ipoib_default_network_tool) == 'netplan'
  when: eseries_ipoib_configure_network

- name: Ensure InfiniBand packages are uninstalled.
  include_tasks: "uninstall/{{ ansible_os_family | lower }}.yml"

- name: Ensure kernel modules are removed.
  modprobe:
    state: absent
    name: "{{ item }}"
  loop: "{{ eseries_ipoib_uninstall_kernel_modules }}"
  become: true
