- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand iSER network interfaces are unconfigured.
  include_tasks: uninstall/interface.yml
  when: eseries_ipoib_configure_network

- name: Ensure InfiniBand base has been uninstalled.
  import_role:
    name: ib_base
    tasks_from: uninstall.yml