- name: Install InfiniBand OpenSM custom packages.
  ansible.builtin.include_role:
    name: netapp_eseries.host.common
    tasks_from: installer/install.yml
    apply:
      vars:
        eseries_common_package_group: "InfiniBand OpenSM"
        eseries_common_custom_packages: "{{ eseries_ib_opensm_custom_packages | default({}) }}"
        eseries_common_allow_upgrades: "{{ eseries_ib_opensm_allow_upgrades | default(false) }}"
        eseries_common_skip_package_validation: "{{ eseries_ib_opensm_skip_package_validation | default(false) }}"
  when: '"install" in (eseries_ib_opensm_custom_packages.keys() | list)'

- name: Load operating system specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand OpenSM packages are installed.
  ansible.builtin.include_tasks: "package/{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand OpenSM subnet managers are configured.
  ansible.builtin.include_tasks: configure.yml