- name: Install InfiniBand OpenSM custom packages.
  ansible.builtin.include_role:
    name: common
    tasks_from: installer/install.yml
  when: '"install" in (eseries_common_custom_packages.keys() | list)'

- name: Load operating system specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand OpenSM packages are installed.
  ansible.builtin.include_tasks: "package/{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand OpenSM subnet managers are configured.
  ansible.builtin.include_tasks: configure.yml