- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Collect facts about systemd services.
  service_facts:
  become: true

- name: Ensure InfiniBand OpenSM service loader for E-Series is stopped and disabled.
  ansible.builtin.systemd:
    name: opensm.service
    state: stopped
    enabled: false
    daemon_reload: true
  when: "'opensm.service' in (ansible_facts['services'].keys() | list)"
  become: true

- name: Ensure InfiniBand packages are uninstalled.
  include_tasks: "uninstall/{{ ansible_os_family | lower }}.yml"

- name: Create InfiniBand OpenSM service loader daemon for E-Series.
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_ib_opensm_daemon_path }}eseries_opensm"
  become: true

- name: Create InfiniBand OpenSM service loader for E-Series.
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_ib_opensm_service_path }}opensm.service"
  become: true

- name: Determine existing OpenSM configuration files.
  find:
    path: "{{ eseries_ib_opensm_config_path }}"
    pattern: "opensm.conf(.[0-9]+)?$"
    use_regex: true
  register: existing_opensm_configs
  become: true

- name: Remove no longer needed OpenSM configuration files.
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  register: delete_opensm_config
  loop: "{{ existing_opensm_configs['files'] }}"
  become: true