- name: Ensure dracut configuration file for multipath has been removed.
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_multipath_dracut_conf_d }}eseries_multipath.conf"
  become: true
  register: dracut_modules

- name: Update initramfs image.
  ansible.builtin.command: dracut --force --omit multipath
  become: true
  when: dracut_modules['changed'] == True

- name: Ensure expected multipath packages have been uninstalled (RHEL).
  ansible.builtin.yum:
    state: absent
    name: "{{ eseries_multipath_rhel_packages }}"
  become: true
