- name: Ensure InfiniBand iSER interfaces configuration files have been removed.
  file:
    state: absent
    path: "{{ eseries_ipoib_netplan_path }}99-eseries-ansible-{{ item['name'] }}.yaml"
  register: netplan
  loop: "{{ eseries_ipoib_interfaces }}"
  become: true

- name: Apply changes to Netplan
  command:
    cmd: netplan apply
  when: netplan['changed']
  become: true

- name: Bring InfiniBand iSER interface down.
  command: ip link set {{ item["name"] }} down
  register: ip_down
  changed_when: ip_down['rc'] != 0 and ip_down['stderr'] is not defined
  failed_when: false
  loop: "{{ eseries_ipoib_interfaces }}"
  become: true

- name: Flush InfiniBand iSER interface.
  command: ip address flush dev {{ item["name"] }}
  register: ip_flush
  changed_when: ip_flush['rc'] != 0 and ip_flush['stderr'] is not defined
  failed_when: false
  loop: "{{ eseries_ipoib_interfaces }}"
  become: true