- name: Determine packages to install (RHEL).
  set_fact:
    rhel_packages: |-
      {%- set packages = [] -%}
      {%- if eseries_ib_base_ipoib_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_rhel_packages["ipoib"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_iser_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_rhel_packages["iser"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_srp_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_rhel_packages["srp"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_nvme_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_rhel_packages["nvme"]) -%}{%- endif -%}
      {%- endif -%}
      {{- packages | unique | sort -}}

- name: Ensure expected InfiniBand base packages are removed (RHEL).
  yum:
    state: absent
    name: "{{ rhel_packages }}"
  become: true
