- name: Determine packages to uninstall (SUSE).
  set_fact:
    suse_packages: |-
      {%- set packages = [] -%}
      {%- if eseries_ib_base_ipoib_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["ipoib"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_iser_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["iser"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_srp_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["srp"]) -%}{%- endif -%}
      {%- endif -%}
      {%- if eseries_ib_base_nvme_enabled == True -%}
        {%- if packages.extend(eseries_ib_base_suse_packages["nvme"]) -%}{%- endif -%}
      {%- endif -%}
      {{- packages | unique | sort -}}

- name: Ensure expected InfiniBand base packages are removed (SUSE).
  community.general.zypper:
    state: absent
    name: "{{ suse_packages }}"
  become: true
