eseries_iscsi_initiator_service: iscsi.service

eseries_ib_iser_default_network_tool: ifupdown

eseries_ib_iser_ifcfg_path: /etc/sysconfig/network/
eseries_ib_iser_netplan_path: /etc/netplan/
eseries_ib_iser_networkd_dispatcher_routable_d_path: /etc/networkd-dispatcher/routable.d/
eseries_ib_iser_networkd_ifup_d_path: /etc/network/if-up.d/

eseries_ib_iser_iface_path: /etc/iscsi/ifaces/
eseries_ib_iser_node_path: /etc/iscsi/nodes/
eseries_ib_iser_static_path: /etc/iscsi/static/

eseries_ib_iser_rdma_memory_conf: /etc/security/limits.d/rdma.conf
