- name: Scan for all mapped volumes.
  import_tasks: host_facts/find_path.yml

- name: Add volume paths to information.
  set_fact:
    eseries_volumes: |-
      {%- set volumes = [] %}
      {%- for volume in initiator_volume_facts -%}
        {%- if volume.update({"path": volume_paths[volume["name"]]["path"],
                              "host_wwid": volume_paths[volume["name"]]["host_wwid"]}) -%}{%- endif -%}
        {%- if volumes.append(volume) -%}{%- endif -%}
      {%- endfor -%}
      {{ volumes | list }}

- name: Add newly mapped volumes from the eseries_mapped_log on the host.
  netapp_eseries.host.file_list:
    file: "{{ eseries_common_mapped_log_path | regex_replace('//*$', '') }}/eseries_mapped_log"
    mode: add
    items: "{{ mapped_volumes }}"
  become: true
  vars:
    mapped_volumes: |-
      {%- set entries = [] -%}
      {%- for volume in eseries_volumes -%}
        {%- set dev_mapper_path = "/dev/mapper/" ~ volume["name"] -%}
        {%- if entries.append(volume["name"] ~ "," ~ volume["path"].split("/")[-1] ~ "," ~ volume["host_wwid"] ~ "," ~ dev_mapper_path) -%}{%- endif -%}
      {%- endfor -%}
      {{- entries -}}

- name: Get currently mapped volumes.
  command:
    cmd: mount
  register: current_mount_info
  changed_when: false
  become: true

- name: Add newly mounted volumes from the mount log.
  netapp_eseries.host.file_list:
    file: "{{ eseries_mount_log_path | regex_replace('//*$', '') }}/eseries_mount_log"
    mode: add
    items: "{{ volume_mounts }}"
  become: true
  vars:
    volume_mounts: |-
      {%- set entries = [] -%}
      {%- for volume in eseries_volumes -%}
        {%- set dev_mapper_path = "/dev/mapper/" ~ volume["name"] -%}
        {%- for line in current_mount_info["stdout_lines"] if dev_mapper_path in line -%}
          {%- set mount_directory = line | regex_replace("^.* on | type .*\(.*\)$", "") -%}
          {%- if entries.append(volume["name"] ~ "," ~ mount_directory ~ "," ~ volume["path"].split("/")[-1] ~ "," ~ volume["host_wwid"] ~ "," ~ dev_mapper_path) -%}{%- endif -%}
        {%- endfor -%}
      {%- endfor -%}
      {{- entries -}}
