- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure iSCSI packages are installed.
  include_tasks: "configure/{{ ansible_os_family | lower }}.yml"

