- name: Configure iSCSI network interfaces
  block:
    - name: Configure iSCSI network interfaces using ifupdown configuration.
      include_tasks: interface/ifupdown.yml
      when: eseries_iscsi_network_tool | default(eseries_iscsi_default_network_tool) == 'ifupdown'

    - name: Configure iSCSI network interfaces using netplan configuration.
      include_tasks: interface/netplan.yml
      when: eseries_iscsi_network_tool | default(eseries_iscsi_default_network_tool) == 'netplan'
  when: eseries_iscsi_configure_network

- name: Configure iSCSI interface bindings.
  import_tasks: interface/iscsi_interface.yml

- name: Set facts for firewall configuration.
  ansible.builtin.set_fact:
    eseries_common_firewall_zone: "{{ eseries_iscsi_firewall_zone | default(eseries_common_firewall_zone | default(omit)) }}"
    eseries_common_interfaces: "{{ eseries_iscsi_interfaces }}"

- name: Apply any interface firewall changes.
  ansible.builtin.include_role:
    name: common
    tasks_from: interface/firewall_zone/install.yml
  when: eseries_common_firewall_zone is defined
