- name: Install iSCSI.
  ansible.builtin.include_tasks: install.yml
  when: not (eseries_common_uninstall | default(eseries_iscsi_uninstall))

- name: Uninstall iSCSI.
  ansible.builtin.include_tasks: uninstall.yml
  when: eseries_common_uninstall | default(eseries_iscsi_uninstall)
