- name: Ensure iSCSI packages are installed and configured.
  import_tasks: configure.yml

- name: Ensure iSCSI interfaces are configured.
  import_tasks: interface.yml

- name: Discover mapped-volume information from associated storage systems.
  import_role:
    name: netapp_eseries.host.common
    tasks_from: volume_facts.yml

- name: Ensure iSCSI sessions are configured and established.
  import_tasks: session.yml
