- name: Ensure iSCSI packages are installed.
  ansible.builtin.import_tasks: package.yml

- name: Ensure iSCSI is configured.
  ansible.builtin.import_tasks: configure.yml

- name: Uninstall iSCSI.
  block:
    - name: Uninstall iSCSI.
      ansible.builtin.include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - iscsi_uninstall
