- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure iSCSI packages are installed.
  import_tasks: package.yml

- name: Ensure iSCSI is configured.
  import_tasks: configure.yml

- name: Ensure iSCSI interfaces are configured.
  import_tasks: interface.yml

- name: Discover mapped-volume information from associated storage systems.
  import_role:
    name: common
    tasks_from: volume_facts.yml

- name: Ensure iSCSI sessions are configured and established.
  import_tasks: session.yml

- name: Uninstall iSCSI.
  import_tasks: uninstall.yml
  tags:
    - never
    - iscsi_uninstall
