- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure iSCSI packages are uninstalled.
  include_tasks: "uninstall/{{ ansible_os_family | lower }}.yml"
