- name: Ensure iSCSI packages are uninstalled.
  ansible.builtin.import_tasks: uninstall/package.yml

- name: Ensure iSCSI is unconfigured.
  ansible.builtin.import_tasks: uninstall/configure.yml

- name: Unconfigure IPoIB interfaces, hooks and firewall configuration.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ip_base
    tasks_from: uninstall.yml
    apply:
      vars:
        eseries_ip_base_configure_network: "{{ eseries_iscsi_configure_network }}"
        eseries_ip_base_configure_firewall: "{{ eseries_iscsi_configure_firewall }}"
        eseries_ip_base_interface_type: "{{ eseries_iscsi_interface_type }}"
        eseries_ip_base_interfaces: "{{ eseries_iscsi_interfaces }}"
        eseries_ip_base_interface_ignore_keys: "{{ eseries_iscsi_interface_ignore_keys }}"
        eseries_ip_base_interface_common: "{{ eseries_iscsi_interface_common }}"
        eseries_ip_base_firewall_zone: "{{ eseries_iscsi_firewall_zone }}"
        eseries_ip_base_default_hook_templates: "{{ eseries_iscsi_default_hook_templates }}"
