eseries_ib_iser_configure_network: true
eseries_ib_iser_configure_firewall: true
# eseries_ib_iser_firewall_zone: # Determined at runtime
eseries_ib_iser_default_hook_templates: []

eseries_ib_iser_udev_name: 99-eseries_ib_iser_udev.rules
eseries_ib_iser_udev_rules: {}

eseries_ib_iser_interface_common: {}
eseries_ib_iser_interface_defaults: {}
eseries_ib_iser_interface_required_keys:
  - name
  - address
eseries_ib_iser_interface_ignore_keys:
  - address
  - hook_template
  - iface
  - node
  - configure
  - mstconfig

# Configuration dictionaries for iscsid.conf (/etc/iscsi/iscsid.conf)
eseries_ib_iser_iscsid_conf_options: {}
eseries_ib_iser_iscsid_conf_group_options: {}
eseries_ib_iser_iscsid_conf_default_options: {}

# Configuration dictionaries for iface files (<iscsi_dir>/iface/<interface>).
eseries_ib_iser_iface_options: {}
eseries_ib_iser_iface_group_options: {}
eseries_ib_iser_iface_default_options:
  # iface.iscsi_ifacename: iser
  iface.transport_name: iser
  iface.port: 3260

# Configuration dictionaries for node files  (<iscsi_dir>/nodes/<target_iqn>/<address>,<port>,[0-9]+/<interface>).
eseries_ib_iser_node_options: {}
eseries_ib_iser_node_group_options: {}
eseries_ib_iser_node_default_options:
  node.startup: automatic
  node.session.nr_sessions: 1
  node.session.queue_depth: 32
  node.session.timeo.replacement_timeout: 20

eseries_ib_iser_uninstall: false  # Whether to uninstall ib_iser role.
