- name: Include operating specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Ensure InfiniBand IPoIB is installed and configured.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ipoib
    apply:
      vars:
        eseries_ib_base_nvme_enabled: true
        eseries_ipoib_configure_network: "{{ eseries_nvme_ib_configure_network }}"
        eseries_ipoib_configure_firewall: "{{ eseries_nvme_ib_configure_firewall }}"
        eseries_ipoib_interfaces: "{{ eseries_nvme_ib_interfaces }}"
        eseries_ipoib_interface_ignore_keys: "{{ eseries_nvme_ib_interface_ignore_keys }}"
        eseries_ipoib_interface_common: "{{ eseries_nvme_ib_interface_common }}"
        eseries_ipoib_interface_defaults: "{{ eseries_nvme_ib_interface_defaults }}"
        eseries_ipoib_firewall_zone: "{{ eseries_nvme_ib_firewall_zone }}"
        eseries_ipoib_default_hook_templates: "{{ eseries_nvme_ib_default_hook_templates }}"

- name: Ensure OpenSM subnet managers are installed and configured.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ib_opensm
    apply:
      vars:
        eseries_ib_opensm_interfaces: "{{ eseries_nvme_ib_interfaces }}"

# IMPORTANT: Refresh storage facts since storage interface statuses will be down until connected with hosts.
- name: Discover mapped-volume information from associated storage systems.
  ansible.builtin.import_role:
    name: netapp_eseries.host.common
    tasks_from: gather_storage_facts.yml

- name: Discover mapped-volume information from associated storage systems.
  ansible.builtin.import_role:
    name: netapp_eseries.host.common
    tasks_from: volume_facts.yml

- name: Ensure NVMe over InfiniBand is configured.
  ansible.builtin.import_tasks: configure.yml

- name: Uninstall InfiniBand IPoIB.
  block:
    - name: Uninstall InfiniBand IPoIB.
      ansible.builtin.include_tasks: uninstall.yml
      when: eseries_common_force_skip_uninstall == False
  tags:
    - never
    - nvme_ib_uninstall
