- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Final host setup for NVMe over InfiniBand protocol.
  debug:
    msg: "Sorry, the NVMe over InfiniBand protocol setup has not been implemented yet."
