- name: Discover mapped-volume information from associated storage systems.
  include_role:
    name: common
    tasks_from: host_facts.yml
  when: eseries_volumes is not defined

- name: Configure multipath for eseries_volumes wwid/aliases.
  block:
    - name: Determine current multipath configuration.
      ansible.builtin.command:
        cmd: multipath -t
      register: current_multipath_configuration
      changed_when: false
      become: true

    - name: Ensure multipath configuration directory exists.
      ansible.builtin.file:
        state: directory
        path: "{{ eseries_multipath_conf_d_path }}"
      become: true

    - name: Configure multipath.conf.
      ansible.builtin.template:
        src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'multipath_conf.j2') }}"
        dest: "{{eseries_multipath_conf_d_path}}eseries_multipath.conf"
      register: multipath_conf
      become: true

    - name: Reload multipathd service.
      ansible.builtin.systemd:
        name: multipathd.service
        state: "{%- if multipath_conf['changed'] %}restarted{%- else %}started{%- endif %}"
        enabled: true
        daemon-reload: true  #"{%- if multipath_conf['changed'] %}true{%- else %}false{%- endif %}"
      become: true

    - name: Update mapped-volume information from associated storage systems.
      include_role:
        name: common
        tasks_from: host_facts.yml
  when: eseries_volumes is defined
