- name: "Ensure multipath has been added to {{ eseries_multipath_dracut_conf_d }}eseries_multipath.conf file."
  template:
    src: configure/eseries_multipath_conf.j2
    dest: "{{ eseries_multipath_dracut_conf_d }}eseries_multipath.conf"
  become: true
  register: dracut_modules

- name: Update initramfs image.
  command: dracut --force
  become: true
  when: dracut_modules['changed'] == True
