- name: Include operating specific variables.
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Host setup for NVMe over Fibre Channel protocol.
  debug:
    msg: "Sorry, the NVMe over Fibre Channel protocol setup has not been implemented yet."
