- import_tasks: initial_setup/package/debian.yml
  when: ansible_facts['os_family'] | lower == 'debian'
  become: true

- import_tasks: initial_setup/package/redhat.yml
  when: ansible_facts['os_family'] | lower == 'redhat'
  become: true

- import_tasks: initial_setup/package/suse.yml
  when: ansible_facts['os_family'] | lower == 'suse'
  become: true
