- name: Collect facts about systemd services.
  service_facts:
  become: true

- name: Unconfigure NVMe over Fibre Channel systemd service.
  systemd:
    name: "{{ eseries_nvme_fc_service_name }}"
    state: stopped
    enabled: false
  when: eseries_nvme_fc_service_name in (ansible_facts['services'].keys() | list)
  become: true

- name: Remove NVMe service daemon.
  file:
    state: absent
    path: "{{ eseries_nvme_fc_daemon_path }}{{ eseries_nvme_fc_daemon_name }}"
  become: true

- name: Remove NVMe systemd service file.
  file:
    state: absent
    path: "{{ eseries_nvme_fc_service_path }}{{ eseries_nvme_fc_service_name }}"
  become: true

- name: Ensure all packages are removed for NVMe over Fibre Channel.
  include_tasks: "uninstall/package/{{ ansible_os_family | lower }}.yml"

- name: Ensure all NVMe over Fibre Channel modules are removed from host.
  include_tasks: uninstall/configure/modules.yml
