eseries_mount_skip_unmount: false

eseries_mount_volumes: ["all_volumes"]
eseries_mount_format_type: xfs
eseries_mount_format_type_options:
  xfs: "-d su=VOLUME_SEGMENT_SIZE_KBk,sw=VOLUME_STRIPE_COUNT -l version=2,su=VOLUME_SEGMENT_SIZE_KBk"
  ext4: "-d su=VOLUME_SEGMENT_SIZE_KBk,sw=VOLUME_STRIPE_COUNT -l version=2,su=VOLUME_SEGMENT_SIZE_KBk"
  btrfs: "-d su=VOLUME_SEGMENT_SIZE_KBk,sw=VOLUME_STRIPE_COUNT -l version=2,su=VOLUME_SEGMENT_SIZE_KBk"

eseries_mount_format_options: "-d su=VOLUME_SEGMENT_SIZE_KBk,sw=VOLUME_STRIPE_COUNT -l version=2,su=VOLUME_SEGMENT_SIZE_KBk"
eseries_mount_persistent_mount_options: "_netdev"  #"noatime,nodiratime,nobarrier,_netdev"
eseries_mount_root_directory: /mnt/
