- name: Install RoCE.
  ansible.builtin.include_tasks: install.yml
  when: not (eseries_common_uninstall | default(eseries_roce_uninstall))

- name: Uninstall RoCE.
  ansible.builtin.include_tasks: uninstall.yml
  when: eseries_common_uninstall | default(eseries_roce_uninstall)
