- name: Ensure the host NVMe Qualified Name (NQN) is correctly set.
  copy:
    content: "{{ eseries_nvme_nqn }}"
    dest: "{{ eseries_nvme_fc_hostnqn }}"
  become: true
  when: eseries_nvme_nqn is defined and eseries_nvme_nqn