- name: Discover mapped-volume information from associated storage systems.
  include_role:
    name: common
    tasks_from: host_facts.yml

- name: Ensure volumes are mounted on hosts.
  include_tasks: collect_facts/unmount.yml

- name: Ensure expected unmounted volumes are not mounted.
  block:
    - name: Collect information for volumes that need to be unmounted
      include_role:
        name: unmount
        tasks_from: collect_info.yml
    - name: Ensure any unmapped volume is unmounted.
      include_role:
        name: unmount
        tasks_from: unmount.yml
  vars:
    eseries_unmount_volumes: "{{ volume_unmount_list }}"
    eseries_unmount_purge: true
  when: eseries_mount_skip_unmount == False and volume_unmount_list | length > 0

- name: Ensure multipath is configured.
  include_role:
    name: multipath
    tasks_from: configure_user_friendly_names.yml

- name: Re-discover mapped-volume information from associated storage systems.
  block:
    - name: Discover mapped-volume information from associated storage systems.
      include_role:
        name: common
        tasks_from: gather_storage_facts.yml
    - name: Discover mapped-volume information from associated storage systems.
      include_role:
        name: common
        tasks_from: volume_facts.yml
    - name: Discover mapped-volume information from associated storage systems.
      include_role:
        name: common
        tasks_from: host_facts.yml

- name: Ensure volumes are mounted on hosts.
  include_tasks: collect_facts/mount.yml

- name: Ensure expected mounted volumes are mounted.
  include_tasks: mount.yml
