- name: Ensure volumes are formatted.
  filesystem:
    fstype: "{{ item['fs_type'] }}"
    opts: "{{ item['fs_options'] }}"
    dev: "{{ item['path'] }}"
  loop: "{{ format_volumes_by_host[inventory_hostname] }}"
  become: true

- name: Ensure volumes are mounted with persistent mount points.
  mount:
    state: mounted
    backup: true
    path: "{{ item['mount_directory'] }}"
    src: "{{ item['path'] }}"
    fstype: "{{ item['fs_type'] }}"
    opts: "{{ item['mount_options'] }}"
  loop: "{{ volume_mount_info }}"
  register: volume_mount
  become: true

