- name: Ensure path for initiatorname.iscsi exists.
  file:
    state: directory
    path: "{{ eseries_iscsi_conf_path }}"
  become: true

- name: Ensure iSCSI initiator name (i.e. IQN) has been set.
  template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'initiatorname_iscsi.j2') }}"
    dest: "{{ eseries_iscsi_conf_path }}initiatorname.iscsi"
  register: initiatorname_iscsi
  become: true
  when: eseries_iscsi_iqn is defined and eseries_iscsi_iqn
