- name: Ensure path for initiatorname.iscsi exists.
  ansible.builtin.file:
    state: directory
    path: "{{ eseries_iscsi_conf_path }}"
  become: true

- name: Ensure iSCSI initiator name (i.e. IQN) has been set.
  ansible.builtin.template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'initiatorname_iscsi.j2') }}"
    dest: "{{ eseries_iscsi_conf_path }}initiatorname.iscsi"
  register: initiatorname_iscsi
  become: true
  when: eseries_iscsi_iqn is defined and eseries_iscsi_iqn

# Note: eseries_iscsi_node_settings is retained for backwards compatibility.
- name: Configure iSCSI settings.
  netapp_eseries.host.update_conf:
    path: "{{ eseries_iscsi_conf_path }}iscsid.conf"
    options: "{{ eseries_iscsi_iscsid_conf_default_options
                 | combine(eseries_iscsi_node_settings | default({}))
                 | combine(eseries_iscsi_iscsid_conf_group_options)
                 | combine(eseries_iscsi_iscsid_conf_options) }}"
    mode: "0600"
  register: iscsid_conf

- name: Start iscsid.service.
  ansible.builtin.systemd:
    name: iscsid.service
    state: "{% if iscsid_conf['changed'] %}restarted{% else %}started{% endif %}"
    daemon-reload: true
    enabled: true
  register: iscsid_service
  become: true
