# example_project/host_vars/eseries_ib_iser_example_array.yml
# Credentials
eseries_proxy_ssid: ib_iser_example_array                       # Storage system identifier for SANtricity Web Services Proxy.
eseries_system_serial: "012345678902"                           # Storage system chassis serial number (located on a label at the top-left towards the front on the device)
eseries_system_password: adminpass                              # Storage system admin password

# Global Settings
eseries_system_name: ib_iser_example_array

# Management Interfaces
eseries_management_interfaces:
  config_method: static
  subnet_mask: 255.255.255.0
  gateway: 192.168.1.1
  controller_a:
    - address: 192.168.1.10
  controller_b:
    - address: 192.168.1.11

# iSCSI interfaces
eseries_initiator_protocol: ib_iser
eseries_controller_ib_iser_port:    # List of iSCSI interface definitions
  controller_a:
    - 192.168.2.100                 # Controller A port 1 IP address
  controller_b:
    - 192.168.3.100                 # Controller B port 1 IP address

# Storage Configuration
eseries_storage_pool_configuration:         # List of storage pools and volume groups definitions
  - name: example_vg1                       # Volume group name
    raid_level: raid6                       # Volume group RAID level (Choices: raid0, raid1, raid5, raid6, raidDiskPool)
    criteria_drive_count: 10                # Number of volumes to add to raid6 volume group
    volumes:                                # List of volume definitions for example_vg1 volume group
      - name: example_vg1_vol_1             # Volume name
        host: eseries_iscsi_example_host    # Ansible inventory host name to map volume
        size: 10                            # Volume size measured in gb
