- name: Collect host mount information for E-Series volumes.
  import_tasks: collect_info.yml

- name: Unmount E-Series volumes from host.
  import_tasks: unmount.yml

- name: Unmap E-Series volume from host.
  include_tasks: unmap.yml
  when: eseries_unmount_unmap == True and eseries_unmount_delete == False

- name: Delete E-Series volumes from host.
  include_tasks: delete.yml
  when: eseries_unmount_delete == True

- name: Ensure multipath user friendly names are configured.
  block:
    - name: Discover mapped-volume information from associated storage systems.
      include_role:
        name: netapp_eseries.host.common
        tasks_from: gather_storage_facts.yml

    - name: Scan for all mapped volumes.
      include_role:
        name: netapp_eseries.host.common
        tasks_from: volume_facts.yml

    - name: Discover mapped-volume information from associated storage systems.
      include_role:
        name: netapp_eseries.host.common
        tasks_from: host_facts.yml

    - name: Ensure multipath user friendly names are configured.
      include_role:
        name: netapp_eseries.host.multipath
        tasks_from: configure_user_friendly_names.yml
  when: eseries_unmount_purge == True or eseries_unmount_unmap == True or eseries_unmount_delete == True
