- name: Unmount all unmapped volumes.
  mount:
    state: unmounted
    path: "{{ item['dev_mapper_path'] }}"
  loop: "{{ unmapped_volume_info }}"
  when: item['dev_mapper_path'] != ''
  become: true

- name: Remove all persistent mount information.
  block:
    - name: Remove mount points for all unmapped volumes.
      mount:
        state: absent
        path: "{{ item['dev_mapper_path'] }}"
      loop: "{{ unmapped_volume_info }}"
      when: item['dev_mapper_path'] != ''
      become: true
  when: eseries_unmount_temporary_unmount == False

- name: Wipe all file system signatures on volume (Fast format).
  include_tasks: wipe.yml
  when: eseries_unmount_wipe_format_signatures == True

- name: Purge volume from host.
  include_tasks: purge.yml
  when: eseries_unmount_purge == True
