- name: Determine required InfiniBand modules.
  set_fact:
    expected_kernel_modules: |-
      {%- set modules = [] -%}
      {%- set module_list = [] -%}

      {%- for module in eseries_ib_base_kernel_modules if module not in module_list -%}
        {%- if modules.append(module) -%}{%- endif -%}
        {%- if module_list.append(module["name"]) -%}{%- endif -%}
      {%- endfor -%}

      {%- if eseries_ib_base_ipoib_enabled == True -%}
        {%- for module in eseries_ib_base_ipoib_kernel_modules if module not in module_list -%}
          {%- if modules.append(module) -%}{%- endif -%}
          {%- if module_list.append(module["name"]) -%}{%- endif -%}
        {%- endfor -%}
      {%- endif -%}

      {%- if eseries_ib_base_iser_enabled == True -%}
        {%- for module in eseries_ib_base_iser_kernel_modules if module not in module_list -%}
          {%- if modules.append(module) -%}{%- endif -%}
          {%- if module_list.append(module["name"]) -%}{%- endif -%}
        {%- endfor -%}
      {%- endif -%}

      {%- if eseries_ib_base_srp_enabled == True -%}
        {%- for module in eseries_ib_base_srp_kernel_modules if module not in module_list -%}
          {%- if modules.append(module) -%}{%- endif -%}
          {%- if module_list.append(module["name"]) -%}{%- endif -%}
        {%- endfor -%}
      {%- endif -%}

      {%- if eseries_ib_base_nvme_enabled == True -%}
        {%- for module in eseries_ib_base_nvme_kernel_modules if module not in module_list -%}
          {%- if modules.append(module) -%}{%- endif -%}
          {%- if module_list.append(module["name"]) -%}{%- endif -%}
        {%- endfor -%}
      {%- endif -%}
      {{- modules -}}

- name: "Ensure {{ eseries_ib_base_rdma }} directory exists."
  file:
    state: directory
    path: "{{ eseries_ib_base_rdma }}"
  become: true

- name: "Ensure {{ eseries_ib_base_rdma }}modules directory exists."
  file:
    state: directory
    path: "{{ eseries_ib_base_rdma }}modules/"
  become: true

- name: "Ensure {{ eseries_ib_base_rdma }}rdma.conf is correct (RHEL)."
  template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'configure/redhat/rdma_conf.j2') }}"
    dest: "{{ eseries_ib_base_rdma }}rdma.conf"
  when: "(ansible_os_family | lower) == 'redhat'"
  become: true

- name: "Ensure {{ eseries_ib_base_rdma }}modules/infiniband.conf is correct."
  template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'configure/infiniband_conf.j2') }}"
    dest: "{{ eseries_ib_base_rdma }}modules/infiniband.conf"
  become: true

- name: "Ensure {{ eseries_ib_base_rdma }}modules/srp_daemon.conf is correct."
  template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'configure/srp_daemon_conf.j2') }}"
    dest: "{{ eseries_ib_base_rdma }}modules/srp_daemon.conf"
  become: true

- name: "Ensure {{ eseries_ib_base_rdma }}modules/rdma.conf is correct."
  template:
    src: "{{ lookup('netapp_eseries.host.eseries_template_path', 'configure/rdma_conf.j2') }}"
    dest: "{{ eseries_ib_base_rdma }}modules/rdma.conf"
  become: true

- name: Ensure required InfiniBand modules are loaded.
  modprobe:
    state: present
    name: "{{ item['name'] }}"
    params: "{{ item['parameters'] }}"
  loop: "{{ expected_kernel_modules }}"
  become: true

- name: Ensure InfiniBand kernel modules have been added to boot.
  template:
    src: configure/eseries_ib_base_conf.j2
    dest: "{{ eseries_ib_base_modules_load_d }}eseries_ib_base.conf"
  become: true

- name: Ensure InfiniBand kernel modules have been added to boot.
  template:
    src: configure/eseries_ib_base_options_conf.j2
    dest: "{{ eseries_ib_base_modules_d }}eseries_ib_base_options.conf"
  become: true
