- name: Ensure hard and soft limit for memlock is unlimited
  community.general.pam_limits:
    dest: "{{ eseries_ib_base_rdma_memory_conf }}"
    domain: "*"
    limit_type: "-"
    limit_item: memlock
    value: unlimited
  become: true
