galaxy_info:
  author: Joe McCormick (@iamjoemccormick)
  description: Configure system settings for maximum performance, possibly at the cost of increased energy usage.
  company: NetApp
  license: BSD-3-Clause
  min_ansible_version: 2.9
  galaxy_tags:
    - netapp
    - eseries
    - performance
    - tuned
dependencies: []
