eseries_ib_opensm_subnet_manager_configure: false
eseries_ib_opensm_subnet_prefix_base: 0xfe80000000000000
eseries_ib_opensm_subnet_priority: 0
eseries_ib_opensm_interfaces: []
eseries_ib_opensm_options: {}      # opensm.conf file key, value pairs
eseries_ib_opensm_allow_upgrades: false
eseries_ib_opensm_skip_package_validation: false
eseries_ib_opensm_ubuntu_packages:
  - opensm

eseries_ib_opensm_suse_packages:
  - opensm

eseries_ib_opensm_rhel_packages:
  - opensm

eseries_ib_opensm_log_path: /var/log/

# Do not use! Internal use only
eseries_common_force_skip_uninstall: false
