eseries_nvme_roce_configure_network: true
eseries_nvme_roce_configure_firewall: true
eseries_nvme_roce_service_name: eseries_nvme_ib.service

eseries_nvme_roce_hostnqn: /etc/nvme/hostnqn
eseries_nvme_roce_modules_load_d: /etc/modules-load.d/
eseries_nvme_roce_modules_d: /etc/modprobe.d/

eseries_nvme_roce_udev_name: 99-eseries_nvme_roce_udev.rules
eseries_nvme_roce_udev_rules: {}  # Dictionary of PCI device-name key-value pairs (example: { "0000:41:00.0": "ib0", "0000:41:00.1": "ib1" })


eseries_nvme_roce_port: 4420
eseries_nvme_roce_queue_depth: 1024
eseries_nvme_roce_controller_loss_timeout: 3600
eseries_nvme_roce_nqn_command: grep -o nqn.* /etc/nvme/hostnqn  # This command must return the system iqn.

eseries_nvme_roce_interface_common: {}
eseries_nvme_roce_interface_defaults: {}

# eseries_nvme_roce_firewall_zone:  # Determined at runtime.
eseries_nvme_roce_default_hook_templates: []
eseries_nvme_roce_interface_required_keys:
  - name
  - address
eseries_nvme_roce_interface_ignore_keys:
  - address
  - hook_template
  - configure
  - mstconfig

eseries_nvme_roce_rhel_packages:
  - rdma-core
  - nvme-cli
eseries_nvme_roce_suse_packages:
  - rdma-core
  - nvme-cli
eseries_nvme_roce_ubuntu_packages:
  - rdma-core
  - nvme-cli

eseries_nvme_roce_kernel_modules:
  - name: nvme-rdma
    parameters:

# Do not use! Internal use only
eseries_common_force_skip_uninstall: false
