- name: Retrieve initiator volume list from E-Series storage systems.
  netapp_eseries.santricity.na_santricity_facts:
    ssid: "{{ hostvars[item]['current_eseries_ssid'] | default(hostvars[item]['eseries_ssid'] | default('1')) }}"
    api_url: "{{ hostvars[item]['current_eseries_api_url'] | default(hostvars[item]['eseries_system_api_url']) }}"
    api_username: "{{ hostvars[item]['current_eseries_api_username'] | default(hostvars[item]['eseries_system_username'] | default('admin')) }}"
    api_password: "{{ hostvars[item]['current_eseries_api_password'] | default(hostvars[item]['eseries_system_password']) }}"
    validate_certs: "{{ hostvars[item]['current_eseries_validate_certs'] | default(hostvars[item]['eseries_validate_certs']) }}"
  loop: "{{ lookup('list', groups[eseries_common_group] | default(eseries_common_group)) }}"
  delegate_to: localhost
  run_once: true
  register: storage_array_facts
