# Note: The when condition is evaluated for each sub-task and find_path.yml sets the conditional values.
#         So, find_path.yml can cause sub-tasks to be skipped and is expected behavior.
- name: Scan for all mapped volumes.
  include_tasks: volume_facts.yml
  when: initiator_volume_facts is not defined

- name: Determine whether multipath is installed.
  command: multipathd show maps
  register: multipathd
  changed_when: false
  failed_when: false
  become: true

- name: Discover multipath devices.
  block:
    - name: Scan for all mapped volumes.
      include_tasks: host_facts/find_path.yml

    - name: Force a rescue when volumes are not available.
      block:
        - name: Volumes are not available...Rescanning SCSI buses.
          include_tasks: host_facts/rescue/rescan_scsi_bus.yml
          when: rescan['iscsi'] or rescan['fc'] or rescan['sas'] or rescan['ib_srp'] or rescan['ib_iser']
        - name: Rescan for all mapped volume paths.
          include_tasks: host_facts/find_path.yml

        - name: Volumes are not available...Rebooting.
          include_tasks: host_facts/rescue/reboot.yml
          when: eseries_common_allow_host_reboot == True

        - name: Rescan for all mapped volume paths.
          include_tasks: host_facts/find_path.yml

        - name: Fail when volumes are not available.
          fail:
            msg: "Failed to discover E-Series volumes!"
      when: rescan['iscsi'] or rescan['fc'] or rescan['sas'] or rescan['ib_srp'] or rescan['ib_iser'] or rescan['nvme_ib'] or rescan['nvme_fc'] or rescan['nvme_roce']

    - name: Add volume paths to volumes
      import_tasks: host_facts/add_path.yml
  when: multipathd["rc"] == 0
