# Note: The when condition is evaluated for each sub-task and find_path.yml sets the conditional values.
#         So, find_path.yml can cause sub-tasks to be skipped and is expected behavior.
- name: Scan for all mapped volumes.
  ansible.builtin.include_tasks: volume_facts.yml
  when: initiator_volume_facts is not defined

- name: Determine whether multipath is installed.
  ansible.builtin.command: systemctl status multipathd.service
  register: multipathd_status
  changed_when: false
  failed_when: false
  become: true

- name: Discover multipath devices.
  block:
    - name: Scan for all mapped volumes.
      ansible.builtin.include_tasks: host_facts/find_path.yml

    - name: Force a rescue when volumes are not available.
      block:
        - name: Volumes are not available...Rescanning SCSI buses.
          ansible.builtin.include_tasks: host_facts/rescue/rescan_scsi_bus.yml
          when: "'rescan_scsi_bus' in rescan_actions"

        - name: Rescan for all mapped volume paths.
          ansible.builtin.include_tasks: host_facts/find_path.yml

        - name: Volumes are not available...Rebooting.
          ansible.builtin.include_tasks: reboot.yml
          vars:
            eseries_common_allow_host_reboot_reason: "Volumes are not available, rebooting..."

        - name: Rescan for all mapped volume paths.
          ansible.builtin.include_tasks: host_facts/find_path.yml

        - name: Fail when volumes are not available.
          ansible.builtin.fail:
            msg: "Failed to discover E-Series volumes!"
      when: "'rescan' in rescan_actions"

    - name: Add volume paths to volumes
      ansible.builtin.include_tasks: host_facts/add_path.yml
  when: multipathd_status["rc"] == 0
