- name: Ensure RDMA is configured.
  ansible.builtin.include_tasks: configure/rdma.yml

- name: Ensure required InfiniBand kernel modules are loaded.
  ansible.builtin.include_tasks: configure/module.yml

# Ansible has a hard limitation where only the parent and the parent-parent role defaults are available to a role's
#   tasks. As a temporary workaround, the _common_udev_X variables are set then cleared to prevent overriding user-defined
#   inventory.
- name: Configure persistent network interface names.
  block:
    - name: Set facts required for configuring persistent network interface names.
      ansible.builtin.set_fact:
        _common_udev_name: "{{ eseries_ib_base_udev_name | default(eseries_ib_udev_name) }}"
        _common_udev_rules: "{{ eseries_ib_base_udev_rules | default(eseries_ib_udev_rules) }}"

    - name: Configure persistent network interface names.
      ansible.builtin.include_role:
        name: netapp_eseries.host.common
        tasks_from: interface/rename_rules/apply.yml

    - name: Clear facts required for configuring persistent network interface names.
      ansible.builtin.set_fact:
        _common_udev_name: ""
        _common_udev_rules: {}

- name: Ensure Mellanox firmware is configured.
  ansible.builtin.include_tasks: configure/firmware.yml
