- name: Set facts required for ib role.
  ansible.builtin.set_fact:
    eseries_common_package_group: "InfiniBand"
    eseries_common_custom_packages: "{{ eseries_ib_custom_packages | default({}) }}"
    eseries_common_allow_upgrades: "{{ eseries_ib_allow_upgrades | default(false) }}"
    eseries_common_skip_package_validation: "{{ eseries_ib_skip_package_validation | default(false) }}"

- name: Install and configure required InfiniBand packages.
  block:
  - name: Install InfiniBand
    ansible.builtin.include_tasks: install.yml
    when: not (eseries_common_uninstall | default(eseries_ib_uninstall))

  - name: Uninstall InfiniBand.
    ansible.builtin.include_tasks: uninstall.yml
    when: eseries_common_uninstall | default(eseries_ib_uninstall)
  when: not eseries_ib_skip
