- name: Set facts required for ib role.
  ansible.builtin.set_fact:
    eseries_common_package_group: "InfiniBand"
    eseries_common_custom_packages: "{{ eseries_ib_custom_packages | default({}) }}"
    eseries_common_allow_upgrades: "{{ eseries_ib_allow_upgrades | default(false) }}"
    eseries_common_skip_package_validation: "{{ eseries_ib_skip_package_validation | default(false) }}"

- name: Install and configure required InfiniBand packages.
  block:
  - name: Install InfiniBand custom packages.
    ansible.builtin.include_role:
      name: netapp_eseries.host.common
      tasks_from: installer/install.yml
    when: '"install" in (eseries_common_custom_packages.keys() | list)'

  - name: Ensure InfiniBand packages are installed.
    ansible.builtin.include_tasks: package.yml

  - name: Ensure InfiniBand is configured.
    ansible.builtin.include_tasks: configure.yml

  - name: Uninstall InfiniBand.
    block:
      - name: Install InfiniBand custom packages.
        ansible.builtin.include_role:
          name: netapp_eseries.host.common
          tasks_from: installer/uninstall.yml
        when: '"uninstall" in (eseries_common_custom_packages.keys() | list)'

      - name: Uninstall InfiniBand.
        ansible.builtin.include_tasks: uninstall.yml
    when: not eseries_common_force_skip_uninstall
    tags:
      - never
      - ib_base_uninstall
  when: not eseries_ib_skip
