- name: Install and configure required InfiniBand packages.
  block:
  - name: Install InfiniBand
    ansible.builtin.include_tasks: install.yml
    when: not (eseries_common_uninstall | default(eseries_ib_uninstall))

  - name: Uninstall InfiniBand.
    ansible.builtin.include_tasks: uninstall.yml
    when: eseries_common_uninstall | default(eseries_ib_uninstall)
  when: not eseries_ib_skip
