- name: Ensure InfiniBand kernel modules are removed.
  include_tasks: "uninstall/configure/module.yml"

- name: Ensure RDMA is unconfigured.
  include_tasks: "uninstall/configure/rdma.yml"

- name: Set facts required for unconfiguring persistent network interface names.
  ansible.builtin.set_fact:
    eseries_common_udev_name: "{{ eseries_ib_udev_name }}"
    eseries_common_udev_rules: "{{ eseries_ib_udev_rules }}"

- name: Unconfigure persistent network interface names.
  ansible.builtin.include_role:
    name: netapp_eseries.host.common
    tasks_from: interface/map_name/uninstall.yml

- name: Ensure InfiniBand packages are uninstalled.
  include_tasks: "uninstall/package/{{ ansible_os_family | lower }}.yml"
