- name: Collect facts about systemd services.
  service_facts:
  become: true

- name: Unconfigure NVMe over Fibre Channel systemd service.
  ansible.builtin.systemd:
    name: srp_daemon.service
    state: stopped
    enabled: false
  when: "'srp_daemon.service' in (ansible_facts['services'].keys() | list)"
  become: true

- name: Delete srp_daemon.service
  ansible.builtin.file:
    state: absent
    path: "{{ eseries_ib_srp_daemon_service }}"
  become: true

- name: Ensure InfiniBand IPoIB is uninstalled.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ib_opensm
    tasks_from: uninstall.yml

- name: Ensure InfiniBand base is uninstalled.
  ansible.builtin.include_role:
    name: netapp_eseries.host.ib_base
    tasks_from: uninstall.yml
