- name: Include operating specific variables.
  ansible.builtin.include_vars: "../../iscsi/vars/{{ ansible_os_family | lower }}/configure/iface.yml"

# This task creates the file that would have been created by the iscsi role's tasks configure/iface.yml and so by skipping that step.
- name: Ensure InfiniBand iSER iSCSI binding exist for each interface.
  ansible.builtin.shell:
    cmd: "iscsiadm -m iface -I iser > {{ eseries_iscsi_iface_path }}{{ item['name'] }}"
    creates: "{{ eseries_iscsi_iface_path }}{{ item['name'] }}"
  register: create_ib_iser_iscsi_bindings
  loop: "{{ eseries_ib_iser_interfaces }}"
  become: true

- name: Set facts required for configuring iSCSI interface bindings.
  ansible.builtin.set_fact:
    eseries_iscsi_interfaces: "{{ eseries_ib_iser_interfaces }}"
    eseries_iscsi_iface_default_options: "{{ eseries_ib_iser_iface_default_options }}"
    eseries_iscsi_iface_group_options: "{{ eseries_ib_iser_iface_group_options }}"
    eseries_iscsi_iface_options: "{{ eseries_ib_iser_iface_options }}"
    eseries_iscsi_tcp_port: "{{ eseries_ib_iser_tcp_port | default() }}"
    eseries_iscsi_queue_depth: "{{ eseries_ib_iser_queue_depth | default() }}"
    eseries_iscsi_nr_session: "{{ eseries_ib_iser_nr_session | default() }}"
    eseries_iscsi_mtu: "{{ eseries_ib_iser_mtu | default() }}"
    eseries_iscsi_session_replacement_timeout: "{{ eseries_ib_iser_session_replacement_timeout | default() }}"
    eseries_iscsi_username: "{{ eseries_ib_iser_username | default() }}"
    eseries_iscsi_password: "{{ eseries_ib_iser_password | default() }}"

- name: Configure iSCSI interface bindings.
  ansible.builtin.include_role:
    role: iscsi
    tasks_from: configure/iface.yml

# This tasks updates ifaces_changed create by the iscsi role's tasks configure/iface.yml
- name: Determine iface configuration files that have been modified.
  ansible.builtin.set_fact:
    ifaces_changed: |-
      {%- set interfaces = ifaces_changed -%}
      {%- for iface in create_ib_iser_iscsi_bindings["results"] if iface['changed'] and iface["item"]["name"] not in interfaces -%}
        {%- if interfaces.append(iface["item"]["name"]) -%}{%- endif -%}
      {%- endfor -%}
      {{- interfaces -}}
