- name: Determine facts for firewall configuration.
  ansible.builtin.set_fact:
    eseries_common_interfaces: "{{ eseries_ip_interfaces }}"
    eseries_common_firewall_zone: "{{ eseries_ip_interface_common['zone'] | default(eseries_ip_firewall_zone | default(eseries_common_firewall_zone | default(''))) }}"

- name: Apply any interface firewall changes.
  ansible.builtin.include_role:
    name: common
    tasks_from: interface/firewall_zone/install.yml
  when: eseries_ip_configure_firewall
