- name: Ensure interface(s) and firewall are configured.
  ansible.builtin.include_tasks: install.yml
  when: not (eseries_common_uninstall | default(eseries_ip_uninstall))

- name: Ensure interface(s) and firewall are unconfigured.
  ansible.builtin.include_tasks: uninstall.yml
  when: eseries_common_uninstall | default(eseries_ip_uninstall)
