- name: Unconfigure network interfaces
  block:
    - name: Determine the network manager (netplan, ifupdown, network_manager, networkd)
      ansible.builtin.include_tasks: get_manager.yml

    - name: Uninstall any Network Manager dispatcher hooks.
      ansible.builtin.include_tasks: uninstall/interface/hook/network_manager.yml
      when: '"network_manager" in eseries_ip_manager_tools'

    - name: Remove network interfaces using ifupdown configuration.
      ansible.builtin.include_tasks: uninstall/interface/ifupdown.yml
      when: '"ifupdown" in eseries_ip_manager_tools'

    - name: Remove network interfaces using netplan configuration.
      ansible.builtin.include_tasks: uninstall/interface/netplan.yml
      when: '"netplan" in eseries_ip_manager_tools'
  when: eseries_ip_configure_network

# Ansible has a hard limitation where only the parent and the parent-parent role defaults are available to a role's
#   tasks. As a temporary workaround, the _common_udev_X variables are set then cleared to prevent overriding user-defined
#   inventory.
- name: Unconfigure persistent network interface names.
  block:
    - name: Set facts required for unconfiguring persistent network interface names.
      ansible.builtin.set_fact:
        _common_udev_name: "{{ eseries_ip_udev_name }}"
        _common_udev_rules: "{{ eseries_ip_udev_rules }}"

    - name: Unconfigure persistent network interface names.
      ansible.builtin.include_role:
        name: netapp_eseries.host.common
        tasks_from: interface/rename_rules/remove.yml

    - name: Clear facts required for unconfiguring persistent network interface names.
      ansible.builtin.set_fact:
        _common_udev_name: "{{ eseries_ip_udev_name }}"
        _common_udev_rules: "{{ eseries_ip_udev_rules }}"

- name: Remove any firewall configuration.
  ansible.builtin.include_tasks: interface/firewall_zone/remove.yml
  when: eseries_ip_configure_firewall
