- name: Unconfigure network interfaces
  block:
    - name: Determine the network manager (netplan, ifupdown, network_manager, networkd)
      ansible.builtin.include_tasks: get_manager.yml

    - name: Uninstall any Network Manager dispatcher hooks.
      ansible.builtin.include_tasks: uninstall/interface/hook/network_manager.yml
      when: '"network_manager" in eseries_ip_manager_tools'

    - name: Remove network interfaces using ifupdown configuration.
      ansible.builtin.include_tasks: uninstall/interface/ifupdown.yml
      when: '"ifupdown" in eseries_ip_manager_tools'

    - name: Remove network interfaces using netplan configuration.
      ansible.builtin.include_tasks: uninstall/interface/netplan.yml
      when: '"netplan" in eseries_ip_manager_tools'
  when: eseries_ip_configure_network

- name: Unconfigure persistent network interface names.
  ansible.builtin.include_role:
    name: netapp_eseries.host.common
    tasks_from: interface/rename_rules/remove.yml

- name: Remove any firewall configuration.
  ansible.builtin.include_tasks: interface/firewall_zone/remove.yml
  when: eseries_ip_configure_firewall
